#!/usr/bin/env python3
"""Normalise BACKLOG.md statuses and regenerate the Index. Idempotent."""
import re, collections

PATH = '/Users/davidhona/dev/franklinwh-local-bridge/BACKLOG.md'
STATES = ('OPEN', 'UNTRIAGED', 'QUEUED', 'PARTIAL', 'BLOCKED', 'HOLD', 'INFO', 'DONE')
ITEM   = re.compile(r'^[A-Z][A-Z0-9]*(-[A-Z0-9]+)+\s+[—-]\s')
STATUS = re.compile(r'^(?:\*\*Status:\*\*|Status:)[ \t]*(.*)$', re.M)
TOKEN  = re.compile(r'^`(' + '|'.join(STATES) + r')`[ \t]*(?:—[ \t]*)?')
DONE   = r'\bdone\b|\bfixed\b|\bshipped\b|\bresolved\b|\bimplemented\b|\bcomplete'
QUEUE  = (r'\bqueued\b|\bplanned\b|\bproposed\b|\bdesigned\b|\bpending\b|\btodo\b'
          r'|\bremaining\b|\bdeferred\b|\bfollow-up\b')

src = open(PATH).read()
src = re.sub(r'\n## Index\n.*?\n---\n\n', '\n', src, count=1, flags=re.S)  # drop old index
L = src.split('\n')

secs = [{'i': i, 'raw': l[3:].rstrip()} for i, l in enumerate(L) if l.startswith('## ')]
for n, s in enumerate(secs):
    s['end']  = secs[n+1]['i'] if n+1 < len(secs) else len(L)
    s['item'] = bool(ITEM.match(s['raw']))
    s['id']   = re.split(r'\s+[—-]\s+', s['raw'])[0].strip() if s['item'] else None
    m = STATUS.search('\n'.join(L[s['i']+1:s['end']]))
    s['st_line'] = m.group(0) if m else None
    s['st'] = (m.group(1).strip() if m else '')

def classify(s):
    """An explicit `TOKEN` wins, so re-runs are stable and hand-edits stick."""
    m = TOKEN.match(s['st'])
    if m:
        return m.group(1), s['st'][m.end():].strip()
    prose = s['st']
    t = (prose + ' || ' + s['raw']).lower()
    d, q = re.search(DONE, t), re.search(QUEUE, t)
    if   'do not start' in t:                                      st = 'HOLD'
    elif 'blocked' in t:                                           st = 'BLOCKED'
    elif d and q:                                                  st = 'PARTIAL'
    elif d:                                                        st = 'DONE'
    elif q:                                                        st = 'QUEUED'
    elif re.match(r'(INFO|ANALYSIS|RESEARCH|PLAN)-', s['id'] or ''):st = 'INFO'
    elif re.search(r'\bongoing\b|\bexplained\b|\binvestigated\b', t):st = 'INFO'
    elif re.match(r'(DEF|BUG|FIX)-', s['id'] or ''):               st = 'OPEN'
    elif prose:                                                    st = 'OPEN'
    else:                                                          st = 'UNTRIAGED'
    return st, prose

for s in secs:
    s['state'], s['prose'] = classify(s) if s['item'] else (None, None)

# ---- rewrite: exactly one canonical Status line per item ----
out, prev = [], 0
for s in secs:
    out.extend(L[prev:s['i']+1])
    body = L[s['i']+1:s['end']]
    if s['item']:
        line = f"**Status:** `{s['state']}`" + (f" — {s['prose']}" if s['prose'] else '')
        if s['st_line'] is not None:
            body = [line if l == s['st_line'] else l for l in body]
        else:
            k = next((j for j, l in enumerate(body) if l.strip()), len(body))
            body = body[:k] + [line, ''] + body[k:]
    out.extend(body)
    prev = s['end']
out.extend(L[prev:])

# ---- index ----
BLURB = {
 'OPEN':      'Live defects — these are the ones that bite users.',
 'UNTRIAGED': 'No state recorded. Needs one before it can be planned.',
 'QUEUED':    'Agreed, not started.',
 'PARTIAL':   'Shipped in part; the remainder is named in the section.',
 'BLOCKED':   'Cannot proceed — the blocker is named in the section.',
 'HOLD':      'Deliberately not to be started yet.',
 'INFO':      'Finding, analysis or standing practice — not a work item.',
 'DONE':      'Shipped. Kept for the reasoning; details in git history.',
}
def anchor(raw):
    return re.sub(r'\s+', '-', re.sub(r'[^\w\s-]', '', raw.lower()).strip())

groups = collections.defaultdict(list)
for s in secs:
    if s['item']:
        groups[s['state']].append(s)

n_items = sum(1 for s in secs if s['item'])
idx = ['## Index', '', f'{n_items} items. Generated by `tools/backlog_index.py` — run it after '
       'editing rather than hand-patching this block.', '']
for st in STATES:
    g = groups.get(st) or []
    if not g:
        continue
    idx += [f'### `{st}` — {len(g)}', '', BLURB[st], '']
    for s in g:
        parts = re.split(r'\s+[—-]\s+', s['raw'], maxsplit=1)
        desc = parts[1] if len(parts) > 1 else ''
        desc = re.sub(r'\s*\((?:queued|DONE|CORE DONE|blocked|DO NOT START)[^)]*\)\s*$', '', desc, flags=re.I)
        desc = re.sub(r'\s*[—-]\s*(?:DONE|FIXED)\b.*$', '', desc)
        idx.append(f'- [{s["id"]}](#{anchor(s["raw"])}) — {desc.strip()}')
    idx.append('')
idx += ['---', '']

text = '\n'.join(out)
cut = text.index('\n---\n') + len('\n---\n')
open(PATH, 'w').write(text[:cut] + '\n' + '\n'.join(idx) + text[cut:])

print(f'{n_items} items,', sum(1 for s in secs if not s['item']), 'non-item sections')
for st in STATES:
    if groups.get(st):
        print(f'  {len(groups[st]):>4}  {st}')
